CREATE TABLE STUDENT(
  EID CHAR(9) PRIMARY KEY NOT NULL,
  firstName CHAR(15) NOT NULL,
  lastName CHAR(15) NOT NULL,
  studentNetID CHAR(10) NOT NULL
);

CREATE TABLE ADVISOR(
  advisorNetID CHAR(10) PRIMARY KEY NOT NULL,
  firstName CHAR(15) NOT NULL,
  lastName CHAR(15) NOT NULL,
  isAdmin BOOLEAN NOT NULL,
  hashedPassword TEXT NOT NULL
);

CREATE TABLE SCHEDULE(
  EID CHAR(9) NOT NULL,
  advisorNetID CHAR(10) NOT NULL,
  scheduleID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  scheduleDate TEXT NOT NULL,
  FOREIGN KEY(EID) REFERENCES STUDENT(EID),
  FOREIGN KEY(advisorNetID) REFERENCES ADVISOR(advisorNetID),
  PRIMARY KEY(scheduleID)
);

CREATE TABLE COURSE(
  CRN CHAR(5) NOT NULL,
  title TEXT NOT NULL,
  courseNO CHAR(5) NOT NULL,
  coursePrefix CHAR(5) NOT NULL,
  term CHAR(12) NOT NULL,
  timeEnd TEXT,
  timeStart TEXT,
  capacity INT,
  actual INT,
  credits FLOAT,
  isHonors INT,
  PRIMARY KEY(CRN, term)
);

CREATE TABLE COURSE_ADVISED(
  CRN CHAR(5) NOT NULL,
  term CHAR(12) NOT NULL,
  scheduleID INT NOT NULL,
  FOREIGN KEY(CRN, term) REFERENCES COURSE(CRN, term),
  FOREIGN KEY(scheduleID) REFERENCES SCHEDULE(scheduleID),
  PRIMARY KEY(CRN, term, scheduleID)
);
