CREATE TABLE STUDENT(
  EID CHAR(9) PRIMARY KEY NOT NULL
    CHECK(length(EID) == 9),
  firstName CHAR(15) NOT NULL,
  lastName CHAR(15) NOT NULL,
  studentNetID CHAR(10) NOT NULL
);

CREATE TABLE ADVISOR(
  advisorNetID CHAR(10) PRIMARY KEY NOT NULL,
  firstName CHAR(15) NOT NULL,
  lastName CHAR(15) NOT NULL,
  isAdmin BOOLEAN NOT NULL
    CHECK (isAdmin IN (0,1)),
  hashedPassword TEXT NOT NULL
);

CREATE TABLE SCHEDULE(
  scheduleID INT PRIMARY KEY NOT NULL AUTOINCREMENT,
  scheduleDate TEXT NOT NULL,
  FOREIGN KEY(EID) REFERENCES STUDENT(EID),
  FOREIGN KEY(advisorNetID) REFERENCES ADVISOR(advisorNetID)
);

CREATE TABLE COURSE_ADVISED(
  CRN CHAR(5) NOT NULL
    CHECK length(CRN) == 5,
  title TEXT NOT NULL,
  TERM TEXT NOT NULL,
  FOREIGN KEY(scheduleID) REFERENCES(SCHEDULE),
  PRIMARY KEY(scheduleID, CRN)
);
